export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_NAME_START = "UPDATE_NAME_START";
export const UPDATE_NAME_CANCEL = "UPDATE_NAME_CANCEL ";
export const UPDATE_NAME_FAILURE = "UPDATE_NAME_FAILURE";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
